version: 2

sources:
  - name: snf_example
    database: SNEAKERFACTORY  
    description: This is a source for bronze shcema, untransformed data
    schema: bronze  
    tables:
      - name: lips
      - name: tcurc
      