version: 2

models:
  - name: KNA1
    columns:
    - name: index
      tests:
        - unique
        - not_null

  - name: t052
    columns:
    - name: index
      tests:
        - unique
        - not_null

  - name: lips
    columns:
    - name: index
      tests:
        - unique
        - not_null